// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAboutFields {
  /** title */
  title: string;

  /** picture */
  picture: Asset;

  /** description1 */
  description1?: string | undefined;

  /** description2 */
  description2?: string | undefined;

  /** description3 */
  description3?: string | undefined;
}

/** About you */

export interface IAbout extends Entry<IAboutFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "about";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomepageFields {
  /** name */
  name: string;

  /** phrase */
  phrase: string;

  /** image */
  image: Asset;
}

export interface IHomepage extends Entry<IHomepageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "homepage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IWorkFields {
  /** songTitle */
  songTitle: string;

  /** songInfo */
  songInfo: Record<string, any>;

  /** releaseInfo */
  releaseInfo: string;

  /** songCover */
  songCover: Asset;

  /** songPlatformApple */
  songPlatformApple?: string | undefined;

  /** songPlatformSpotify */
  songPlatformSpotify?: string | undefined;
}

/** Discography, catalogue. */

export interface IWork extends Entry<IWorkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "work";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "about" | "homepage" | "work";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
